uavcan.node.id: 1
uavcan.pub.udral.esc.0.id: 111
uavcan.pub.udral.readiness.0.id: 112
uavcan.pub.udral.imu.0.id: 123
uavcan.sub.uorb.sensor_gps.0.id: 2001
uavcan.pub.uorb.sensor_gps.0.id: 2002
uavcan.sub.udral.mag.0.id: 2402
uavcan.sub.udral.baro.temperature.0.id: 2403
uavcan.sub.udral.baro.pressure.0.id: 2404
uavcan.sub.udral.gps.0.id: 2406
uavcan.sub.udral.gps.sats.0.id: 2407
uavcan.sub.udral.gps.status.0.id: 2408
uavcan.sub.udral.gps.pdop.0.id: 2409
uavcan.sub.udral.battery_parameters.0.id: 4098
uavcan.sub.udral.battery_status.0.id: 4097
uavcan.sub.udral.energy_source.0.id: 4096
uavcan.sub.udral.legacy_bms.0.id: 4095
